### ISSUE TITLE
Make model and plot classes

### ISSUE THREAD

**Issue by malonej501** [ohjade/pk_project#1]
Turn code in prototype.py into a set of classes in model.py

**Comment by malonej501** [comment]
The initial classes have now been made, and the model generates a graph for qc and qp1 against time for one set of parameters. Now need to add more functionality, such as being able to alter the number of compartments and the dosing method (i.e. intravenous or subcutaneous).

**Comment by malonej501** [comment]
Added the above features, you can now specify the number of compartments and dosage method and generate the resulting graphs.

**Comment by ZhengyangSun1020** [comment]
The model script is amazing! 
For convenient use and checking, I moved the protocol, solution, and plot functions to individual Python files.
